language: java
jdk:
  - openjdk8
services:
  - mysql
before_install:
    - mysql -u root -e 'CREATE DATABASE IF NOT EXIST test;'
    - mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost' IDENTIFIED BY 'test';"
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
